# List of crafting recipes and all materials required. Recipes pulled from Serebii.
rec = {
    "poke ball": {"apricorn": 1, "tumblestone": 1},
    "great ball": {"apricorn": 1, "iron chunk": 1, "tumblestone": 1},
    "ultra ball": {"apricorn": 1, "iron chunk": 2, "tumblestone": 2},
    "heavy ball": {"apricorn": 1, "black tumblestone": 1},
    "leaden ball": {"apricorn": 1, "black tumblestone": 1, "iron chunk": 1},
    "gigaton ball": {"apricorn": 1, "black tumblestone": 2, "iron chunk": 2},
    "feather ball": {"apricorn": 1, "sky tumblestone": 1},
    "wing ball": {"apricorn": 1, "sky tumblestone": 1, "iron chunk": 1},
    "jet ball": {"apricorn": 1, "sky tumblestone": 2, "iron chunk": 2},
    "aux power": {"swordcap": 2, "pep-up plant": 1},
    "aux guard": {"iron barktongue": 2, "pep-up plant": 1},
    "aux powerguard": {"aux power": 1, "aux guard": 1, "king's leaf": 1},
    "aux evasion": {"doppel bonnets": 2, "candy truffle": 1},
    "dire hit": {"direshroom": 2, "candy truffle": 1},
    "choice dumpling": {"caster fern": 3, "direshroom": 1, "swordcap": 1, "hearty grains": 2},
    "swap snack": {"candy truffle": 1, "sootfoot root": 1, "springy mushroom": 1, "hopo berry": 1},
    "twice-spiced radish": {"sand radish": 2, "crunchy salt": 2, "plump beans": 2, "king's leaf": 2},
    "potion": {"oran berry": 1, "medicinal leek": 1},
    "super potion": {"potion": 1, "pep-up plants": 1},
    "hyper potion": {"super potion": 1, "vivichoke": 1},
    "max potion": {"sitrus berry": 1, "king's leaf": 1},
    "remedy": {"bugwort": 2},
    "fine remedy": {"remedy": 1, "pep-up plants": 1},
    "superb remedy": {"fine remedy": 1, "vivichoke": 1},
    "full heal": {"cheri berry": 1, "pecha berry": 1, "rawst berry": 1, "aspear berry": 1},
    "full restore": {"max potion": 1, "full heals": 1},
    "revive": {"vivichoke": 1, "medicinal leek": 2},
    "max revive": {"revive": 1, "king's leaf": 1},
    "max ether": {"leppa berry": 1, "pep-up plants": 2},
    "max elixir": {"max ether": 1, "king's leaf": 2},
    "jubilife muffin": {"hearty grains": 2, "hopo berry": 2, "razz berry": 1, "cake-lure bases": 1},
    "old gateau": {"plump beans": 1, "dazzling honey": 1, "sootfoot root": 1, "cake-lure bases": 1},
    "bean cake": {"plump beans": 1, "cake-lure base": 1},
    "grain cake": {"hearty grains": 1, "cake-lure base": 1},
    "honey cake": {"dazzling honey": 1, "cake-lure base": 1},
    "mushroom cake": {"springy mushroom": 1, "cake-lure base": 1},
    "salt cake": {"crunchy salt": 1, "cake-lure base": 1},
    "pokeshi doll": {"wood": 3},
    "scatter bang": {"pop pod": 1, "caster fern": 1},
    "smoke bomb": {"caster fern": 1, "sootfoot root": 1},
    "star piece": {"red shard": 3, "blue shard": 3, "green shard": 3, "stardust": 1},
    "stealth spray": {"hopo berry": 1, "bugwort": 3},
    "sticky glob": {"spoiled apricorn": 1, "ball of mud": 1, "caster fern": 1}
}